### ISSUE TITLE
Generated trkpt looks not valid

### ISSUE THREAD

**Issue by vbouchet31** [fabulator/endomondo-api-handler#130] opened 2020-01-14 14:52 UTC
Hi,

I exported some of my workouts using the script. When I tried to import these in my Garmin account, it was said being invalid.
When opening the generated gpx, it appears the points only contain the latitude/longitude but nothing more (no time, no hr, no elevation, etc).
I downloaded the same workout from Endomondo directly and the points contain the time.

This is the workout I used as example: https://www.endomondo.com/users/1863517/workouts/282212961 (public).

I attached the downloaded and generated files to help investigation. I had to zip these together given Github does not accept gpx files.
[workout.zip](https://github.com/fabulator/endomondo-api-handler/files/4059732/workout.zip)

**Comment by vbouchet31** [comment] 2020-01-16 07:45
I forgot to mention that I simply used the example script:
```
await api.processWorkouts({}, (workout) => {
  console.log(workout.toString());
  if (workout.hasGPSData()) {
    fs.writeFileSync(`tmp/${workout.getId()}.gpx`, workout.toGpx(), 'utf8');
  }
});
```

**Comment by fabulator** [comment] 2020-01-21 12:55
I checked it and I think there is some problem with authorization. Your workout is publicly visible. When I check API response of your workout (https://www.endomondo.com/rest/v1/users/1863517/workouts/282212961) I can see in points latitude and longitude but not the time. Only you as a logged user can see the time values for you workouts. So that is why it's missing in export.

Try to make a workout private and check if script still works. If not there is some problem with authorization. Are you using login method?

**Comment by vbouchet31** [comment] 2020-01-22 07:47
Hi @fabulator,

Yes, despite the workout being public, I always used the login method. I pasted here only part of the my script but I was using `await api.login(<email>,<password>);`.

My workout has been to use:
```
api.getWorkoutTcx(workout.getId(), workout.getSource().author.id).then(function(tcx) {
  <save to a file>
}
```

**Comment by fabulator** [comment] 2020-01-22 09:03
I think this is now mixed with a second issue with a tcx format. Let me just verify what is the difference between workout.toGpx() and api.getWorkoutGpx . 
workout.toGpx is generated from JSON Endomondo response eg. https://www.endomondo.com/rest/v1/users/1863517/workouts/282212961 There is the list of points and from this list the gpx file is generated by app.

api.getWorkoutGpx is pure request to endomondo eg.
https://www.endomondo.com/rest/v1/users/5635433/workouts/1454704685/export?format=GPX and it's not processed by library. 

What I understand you're using getWorkoutTcx and besides the ID problem, it's working fine. I think that missing time in workout.toGpx was just some problem with authentication I cannot reproduce. right now. So I will close the issue. Feel free to open it if you have additional thoughts.

btw. you don't have to use the second parameter in getWorkoutTcx, it's only optional. By default it uses id of logged user.

**Closed by fabulator** 2020-01-22 09:03 UTC
